### ISSUE TITLE
Set is missing diff and intersect

### ISSUE THREAD

**Issue by mavnn** [rtfeldman/elm-sorter-experiment#2]
What it says on the tin, basically! It makes it harder to update from the standard Set module.

**Comment by rtfeldman** [comment]
This is actually intentional! https://github.com/rtfeldman/elm-sorter-experiment/blob/master/README.md#other-set-api-changes

Should be a (more or less) drop-in replacement. 😄

**Comment by mavnn** [comment]
So, apparently reading comprehension is for other days of the week :doh:

I'll use those then, shall I?
